"""Verify the truncation trick end-to-end before ONNX submission.

The submission contract feeds the grader's own z ~ N(0, I) into the exported
graph, so truncation cannot be applied outside the model. Instead it is BAKED
INTO the graph: the wrapper scales z by psi (< 1) before G, shrinking every
latent toward the prior mean (the high-fidelity region) inside submission.onnx.
From the grader's side it is still z -> image, so the contract is satisfied.

Mid-fade caveat (e.g. ckpt_001150352.pt at 1024 fade, alpha ~ 0.5):
    The training samples that looked good were produced with the FADE BLEND
    G(z, resolution=1024, alpha~0.5) = (1-a)*upsample(toRGB_512) + a*toRGB_1024.
    The default wrapper calls G(z) with no args, which takes the full-1024
    (alpha=1.0) path and drops the upsampled-512 crutch -> you lose exactly the
    look that made the checkpoint good. So the wrapper also bakes in a fixed
    (resolution, alpha). The fade blend is still a 1024x1024 image in [-1, 1],
    so it satisfies the contract.

What this script does:
    1. Local A/B  -- render fixed-z sample grids over (alpha, psi) so you can
                     pick the most natural-looking combo by eye.
    2. ONNX check -- export the chosen combo and assert onnxruntime output
                     matches the PyTorch wrapper, proving the trick is correctly
                     frozen into submission.onnx.

Run from the repo root (where src/ and export_onnx.py live):
    pip install onnxruntime          # if not already present
    python verify_truncation.py
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.utils as vutils

from src.model import Generator, GeneratorConfig


# ----------------------------- configuration ----------------------------- #
CKPT_PATH = Path(
    "/content/drive/MyDrive/OpenAILab/project2/pggan_1024_v2/ckpt_001150352.pt"
)
OUT_DIR = Path("runs/truncation_ab")

SEED = 42
NUM_SAMPLES = 16            # faces per grid
GRID_NROW = 8

# How a sub-1024 generation is scaled up to the 1024 contract size.
# bicubic is sharper-yet-smooth; bilinear softer; nearest blocky. A no-op when
# the generation is already 1024 (native-1024 or fade-blend paths).
UPSAMPLE_MODE = "bicubic"

# A/B strategies for constructing the 1024 image: (name, gen_resolution, alpha).
#   gen_resolution=None        -> full native-1024 path (alpha ignored)
#   gen_resolution=512         -> clean native 512, then upsampled to 1024
#   gen_resolution=1024, a<1   -> progressive fade blend at 1024
STRATEGIES = [
    ("pure512", 512, 1.0),
    ("blend1024_a0.50", 1024, 0.5),
    ("native1024", None, 1.0),
]
PSIS = [1.0, 0.7, 0.6, 0.5]

DISPLAY_RESOLUTION = 256   # downscale faces just for the preview grid

# The combo to freeze into submission.onnx for the ONNX round-trip check.
# Set these to whatever the A/B grids show is best (match a STRATEGIES row).
EXPORT_GEN_RESOLUTION = 512   # None -> native 1024; 512 -> pure-512 upscaled
EXPORT_ALPHA = 1.0
EXPORT_PSI = 0.7
EXPORT_PATH = Path("submission.onnx")

# Preview generated by running the EXPORTED submission.onnx itself (seed 42).
# This is what the grader's pipeline actually sees -- judge quality from here.
ONNX_PREVIEW_PATH = OUT_DIR / "submission_onnx_seed42.png"
ONNX_PREVIEW_SEED = 42
ONNX_PREVIEW_SAMPLES = 16
# ------------------------------------------------------------------------- #


def load_generator(ckpt_path: Path) -> Generator:
    """Load the EMA generator and its architecture from a training checkpoint."""
    ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=False)
    g_cfg = GeneratorConfig.from_dict(ckpt["meta"]["generator_config"])
    generator = Generator(g_cfg)
    generator.load_state_dict(ckpt["G_ema_state"])
    generator.eval()
    return generator


class TruncationWrapper(nn.Module):
    """Bake truncation (z*psi), the 1024-construction path, and the upsample
    mode into the graph.

    This is the exact module that gets exported, so whatever it does is frozen
    into submission.onnx. The grader passes plain z ~ N(0, I); inside the graph
    it becomes z*psi, runs G at gen_resolution, and is scaled to 1024.
    """

    def __init__(
        self,
        generator: Generator,
        *,
        psi: float = 1.0,
        gen_resolution: int | None = None,
        alpha: float = 1.0,
        upsample_mode: str = "bicubic",
    ) -> None:
        super().__init__()
        self.generator = generator
        self.psi = float(psi)
        self.gen_resolution = gen_resolution
        self.alpha = float(alpha)
        self.upsample_mode = upsample_mode
        # export_onnx checks G.z_dim == 512; expose it on the wrapper too.
        self.z_dim = generator.z_dim

    def forward(self, z: torch.Tensor) -> torch.Tensor:
        z = z * self.psi                                    # (B, 512) -> (B, 512)
        if self.gen_resolution is None:
            image = self.generator(z)                       # (B, 512) -> (B, 3, 1024, 1024)
        else:
            image = self.generator(
                z, resolution=self.gen_resolution, alpha=self.alpha
            )                                               # (B, 512) -> (B, 3, gen, gen)
        image = F.interpolate(
            image,
            size=(1024, 1024),
            mode=self.upsample_mode,
            align_corners=False,
        )                                                   # (B, 3, gen, gen) -> (B, 3, 1024, 1024)
        return image


@torch.no_grad()
def render_ab_grids(generator: Generator, device: torch.device) -> None:
    """Render one preview grid per (strategy, psi) combo using a fixed latent."""
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    sample_z = torch.randn(
        NUM_SAMPLES, generator.z_dim,
        generator=torch.Generator().manual_seed(SEED),
    ).to(device)                                            # (NUM_SAMPLES, 512)

    for name, gen_resolution, alpha in STRATEGIES:
        for psi in PSIS:
            wrapper = TruncationWrapper(
                generator, psi=psi, gen_resolution=gen_resolution,
                alpha=alpha, upsample_mode=UPSAMPLE_MODE,
            ).to(device).eval()

            fake = wrapper(sample_z)                         # (N, 3, 1024, 1024)
            fake = F.interpolate(
                fake,
                size=(DISPLAY_RESOLUTION, DISPLAY_RESOLUTION),
                mode="bilinear",
                align_corners=False,
            )                                               # (N, 3, 256, 256)
            image = ((fake + 1.0) / 2.0).clamp(0.0, 1.0)
            grid = vutils.make_grid(image, nrow=GRID_NROW, padding=2)
            out_path = OUT_DIR / f"{name}_psi{psi:.2f}.png"
            vutils.save_image(grid, out_path)
            print(f"[grid] {out_path}")


def render_from_onnx(session, z_dim: int) -> None:
    """Generate a seed-42 grid by running the exported ONNX itself.

    This is the most faithful check: it runs the actual submission artifact, so
    the faces here are exactly what the grader's pipeline produces.
    """
    sample_z = torch.randn(
        ONNX_PREVIEW_SAMPLES, z_dim,
        generator=torch.Generator().manual_seed(ONNX_PREVIEW_SEED),
    ).numpy()                                               # (16, 512)
    image = session.run(["image"], {"z": sample_z})[0]      # (16, 3, 1024, 1024)

    image = torch.from_numpy(image)
    image = F.interpolate(
        image,
        size=(DISPLAY_RESOLUTION, DISPLAY_RESOLUTION),
        mode="bilinear",
        align_corners=False,
    )                                                       # (16, 3, 256, 256)
    image = ((image + 1.0) / 2.0).clamp(0.0, 1.0)
    grid = vutils.make_grid(image, nrow=GRID_NROW, padding=2)
    ONNX_PREVIEW_PATH.parent.mkdir(parents=True, exist_ok=True)
    vutils.save_image(grid, ONNX_PREVIEW_PATH)
    print(f"[onnx] seed-{ONNX_PREVIEW_SEED} preview from submission.onnx "
          f"-> {ONNX_PREVIEW_PATH}")


def verify_onnx(generator: Generator) -> None:
    """Export the chosen combo and assert ONNX output matches PyTorch."""
    import onnxruntime as ort

    wrapper = TruncationWrapper(
        generator, psi=EXPORT_PSI, gen_resolution=EXPORT_GEN_RESOLUTION,
        alpha=EXPORT_ALPHA, upsample_mode=UPSAMPLE_MODE,
    ).cpu().eval()

    dummy_z = torch.randn(1, generator.z_dim)               # (1, 512)
    EXPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    torch.onnx.export(
        wrapper,
        dummy_z,
        str(EXPORT_PATH),
        input_names=["z"],
        output_names=["image"],
        opset_version=17,
        dynamic_axes={"z": {0: "batch"}, "image": {0: "batch"}},
        dynamo=False,
    )
    print(f"[onnx] exported -> {EXPORT_PATH} "
          f"(psi={EXPORT_PSI}, gen_resolution={EXPORT_GEN_RESOLUTION}, "
          f"alpha={EXPORT_ALPHA}, upsample={UPSAMPLE_MODE})")

    # Round-trip: same z through PyTorch wrapper and onnxruntime must agree.
    check_z = torch.randn(
        4, generator.z_dim,
        generator=torch.Generator().manual_seed(SEED + 1),
    )                                                       # (4, 512)
    with torch.no_grad():
        torch_out = wrapper(check_z).numpy()                # (4, 3, 1024, 1024)

    session = ort.InferenceSession(
        str(EXPORT_PATH), providers=["CPUExecutionProvider"]
    )
    onnx_out = session.run(["image"], {"z": check_z.numpy()})[0]

    max_abs_diff = float(np.abs(onnx_out - torch_out).max())
    print(f"[onnx] output shape {onnx_out.shape}, "
          f"range [{onnx_out.min():.3f}, {onnx_out.max():.3f}]")
    print(f"[onnx] max |onnx - torch| = {max_abs_diff:.2e}")
    assert max_abs_diff < 1e-3, "ONNX output diverges from PyTorch wrapper"

    # Sanity: with psi<1 the truncated graph must differ from the same path at
    # psi=1.0 (no truncation), proving z*psi actually changed the output.
    if EXPORT_PSI < 1.0:
        raw_wrapper = TruncationWrapper(
            generator, psi=1.0, gen_resolution=EXPORT_GEN_RESOLUTION,
            alpha=EXPORT_ALPHA, upsample_mode=UPSAMPLE_MODE,
        ).cpu().eval()
        with torch.no_grad():
            raw_out = raw_wrapper(check_z).numpy()
        truncation_effect = float(np.abs(onnx_out - raw_out).max())
        print(f"[onnx] truncation effect vs psi=1.0: {truncation_effect:.3e} "
              f"(should be clearly > 0)")

    print("[onnx] round-trip OK -- truncation is correctly baked into the graph.")

    # The actual artifact you submit, rendered with seed 42 so you can judge it.
    render_from_onnx(session, generator.z_dim)


def main() -> None:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    generator = load_generator(CKPT_PATH).to(device)
    print(f"Loaded G_ema from {CKPT_PATH.name} (z_dim={generator.z_dim})")

    render_ab_grids(generator, device)
    verify_onnx(generator.cpu())


if __name__ == "__main__":
    main()
